dist: xenial
language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"

env:
  - database=asn format=binary
  - database=asn format=csv
  - database=city format=binary
  - database=city format=csv
  - database=country format=binary
  - database=country format=csv

script:
  - ./maxmind.py --database="$database" --format="$format"
  - ls GeoLite2*
